# Generated by Django 5.2.7 on 2025-11-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiming', '0003_aboutdetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutdetail',
            options={},
        ),
        migrations.RemoveField(
            model_name='aboutdetail',
            name='order',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='role',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='experience_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='experience',
            field=models.IntegerField(choices=[(1, 'Basic (Name & Image)'), (2, 'Experience Details')], default=1),
        ),
    ]
