# Generated by Django 5.2.7 on 2025-11-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiming', '0004_alter_aboutdetail_options_remove_aboutdetail_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='experience',
            field=models.IntegerField(choices=[(1, 'Basic (Name & Image)'), (2, 'Technical Referee Experience'), (3, 'Team Leadership Experience')], default=1),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
