# Generated by Django 5.2.7 on 2025-11-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiming', '0006_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
