# Generated by Django 5.2.7 on 2025-11-06 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swiming', '0007_alter_hero_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hero',
            options={},
        ),
        migrations.RemoveField(
            model_name='hero',
            name='order',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='title',
        ),
    ]
