# Generated by Django 5.2.7 on 2025-11-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiming', '0008_alter_hero_options_remove_hero_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Main phone number', max_length=100)),
                ('telegram_khmer', models.CharField(help_text='Telegram for Khmer speaking', max_length=100)),
                ('telegram_english', models.CharField(help_text='Telegram for English speaking', max_length=100)),
                ('email', models.EmailField(help_text='Contact email', max_length=254)),
                ('address_link', models.URLField(help_text='Google Maps link')),
                ('monday_friday_hours', models.CharField(default='6:00 AM - 19:00 PM', max_length=50)),
                ('saturday_sunday_hours', models.CharField(default='6:00 AM - 18:00 PM', max_length=50)),
                ('pool_location', models.CharField(default='Olympic Stadium / Khmer Swimming Federation', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
    ]
